### ISSUE TITLE
Support Beta Versions of Plugins

### ISSUE THREAD

**Issue by mathetos** [impress-org/wp-rollback#13]
This is an interesting plugin which gives you an alert when there's a beta version of a plugin available. Would be a nice addition to ours:
https://wordpress.org/plugins/plugin-beta-tester/

**Comment by icryptic** [comment]
It was removed from the repo

**Comment by mathetos** [comment]
Keep in mind, testing beta versions is technically possible already:
https://wordimpress.com/beta-testing-wordpress-plugins-with-wp-rollback/

**Comment by Shelob9** [comment]
FYI I use WP Rollback for this -- tag a beta on .org without changing stable tag. Works pretty good.

**Comment by DevinWalker** [comment]
@Shelob9 can you give me an example plugin that I can test it with?

**Comment by DevinWalker** [comment]
This is resolved with #47
