### ISSUE TITLE
Use wp.org plugins API to get theme version information

### ISSUE THREAD

**Issue by drrobotnik** [impress-org/wp-rollback#35]
Currently to build the SVN version information we scrape the page and parse the html. WordPress does have an API for querying this information. 

Example:
https://api.wordpress.org/plugins/info/1.0/wp-rollback.json

Proposing we refactor `get_svn_tags` and `set_svn_versions_data` to use the API. This would also be a step towards implementing #7 since changelog information is included.

**Comment by drrobotnik** [comment]
Themes does not return version tags, so might not be able to remove svn_tag functions entirely.

**Comment by DevinWalker** [comment]
Sounds like some good optimization. Want to take this one on?
