### ISSUE TITLE
fix: use load_plugin_textdomain as primary localization function

### ISSUE THREAD

**Issue by mathetos** [impress-org/wp-rollback#48]
# Bug Report

## User Story

As a WP Rollback user, I want to be able to localize the strings properly. 

[As reported here](https://wordpress.org/support/topic/load_textdomain-error/) using `load_plugin_textdomain` only as a fallback prevents localization with some plugins like Codestyling Localization. 

The function is found here
https://github.com/impress-org/wp-rollback/blob/c4daddf1bf930f48eae31238c5fca1a615262874/wp-rollback.php#L327-L336

The way we load it in Give seems streamlined and updated:
https://github.com/impress-org/give/blob/bc08fb851b6b7a856ce6ea0936713a59b64490f6/give.php#L621-L623

**Comment by DevinWalker** [comment]
I just tested if translations are working properly and they are. We're only using `load_plugin_textdomain` as a fallback. Translations are also coming in fine in GlotPress: https://translate.wordpress.org/projects/wp-plugins/wp-rollback/
